
default: help
.PHONY: default

help:
	@echo 'Usage:'
	@echo '	$$ make [action]'
	@echo
	@echo 'Ex:'
	@echo '	$$ make'
	@echo '	$$ make help'
	@echo
	@echo '	$$ make prepare'
	@echo
	@echo '	$$ make create'
	@echo
	@echo '	$$ make extract'
	@echo
	@echo '	$$ make clean'
	@echo
.PHONY: help




prepare:
	@./prepare.sh
.PHONY: prepare


create:
	@./create.sh
.PHONY: create


extract:
	@./extract.sh
.PHONY: extract


clean:
	@./clean.sh
.PHONY: clean
